"""create chat table

Revision ID: a5677e324830
Revises:
Create Date: 2022-12-25 14:14:11.051077

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5677e324830"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("workbook_url", sa.Text(), nullable=True),
        sa.Column("worksheet_name", sa.Text(), nullable=True),
        sa.Column("default_currency", sa.Text(), nullable=True),
        sa.Column("creation_time", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat")
    # ### end Alembic commands ###
